version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: meu-postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecreto
      POSTGRES_DB: minha_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: